// Mocks generated by Mockito 5.4.4 from annotations
// in treinamento_mvvm/test/request_api_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:treinamento_mvvm/core/request/request.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RequestApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestApiService extends _i1.Mock implements _i2.RequestApiService {
  MockRequestApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isToPrintRequest => (super.noSuchMethod(
        Invocation.getter(#isToPrintRequest),
        returnValue: false,
      ) as bool);

  @override
  bool get isToPrintBody => (super.noSuchMethod(
        Invocation.getter(#isToPrintBody),
        returnValue: false,
      ) as bool);

  @override
  bool get isToPrintToken => (super.noSuchMethod(
        Invocation.getter(#isToPrintToken),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<Map<String, dynamic>?> request(
    _i2.RequestsType? requestsType,
    Uri? uri, {
    String? token = r'',
    Object? body,
    String? entity = r'',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [
            requestsType,
            uri,
          ],
          {
            #token: token,
            #body: body,
            #entity: entity,
          },
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<String> requestString(
    _i2.RequestsType? requestsType,
    Uri? uri, {
    String? token = r'',
    Object? body,
    String? entity = r'',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestString,
          [
            requestsType,
            uri,
          ],
          {
            #token: token,
            #body: body,
            #entity: entity,
          },
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #requestString,
            [
              requestsType,
              uri,
            ],
            {
              #token: token,
              #body: body,
              #entity: entity,
            },
          ),
        )),
      ) as _i3.Future<String>);
}
