// Mocks generated by Mockito 5.4.4 from annotations
// in treinamento_mvvm/test/request_api_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:treinamento_mvvm/core/request/request.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RequestApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestApiService extends _i1.Mock implements _i3.RequestApiService {
  MockRequestApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<Map<String, dynamic>?> request(
    _i3.RequestsType? requestsType,
    Uri? uri, {
    String? token = r'',
    Object? body,
    String? entity = r'',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [
            requestsType,
            uri,
          ],
          {
            #token: token,
            #body: body,
            #entity: entity,
          },
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<_i2.Response> requestType(
    _i3.RequestsType? requestsType,
    Uri? uri,
    String? token,
    Object? body,
    String? entity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestType,
          [
            requestsType,
            uri,
            token,
            body,
            entity,
          ],
        ),
        returnValue: _i4.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #requestType,
            [
              requestsType,
              uri,
              token,
              body,
              entity,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Response>);
}
